# Generated by Django 3.2.3 on 2024-12-05 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.basemodel')),
                ('unit_of_measurement', models.CharField(choices=[('KG', 'Killograms'), ('GR', 'Grams'), ('MG', 'Milligrams'), ('L', 'Liters'), ('ML', 'Milliliters'), ('SM', 'Small spoon'), ('LS', 'Large spoon')], max_length=25)),
            ],
            bases=('recipes.basemodel',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.basemodel')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            bases=('recipes.basemodel',),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.basemodel')),
                ('image', models.ImageField(default=None, null=True, upload_to='recipes/images/', verbose_name='Изображение')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('cooking_time', models.TimeField()),
                ('ingredient', models.ManyToManyField(related_name='ingredients', to='recipes.Ingredient', verbose_name='Ингредиент')),
                ('tag', models.ManyToManyField(related_name='tags', to='recipes.Tag', verbose_name='Тэг')),
            ],
            bases=('recipes.basemodel',),
        ),
    ]
