# Generated by Django 3.2.3 on 2025-01-20 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=150, message='Максимальная длина названия рецепта - 150 символов.')], verbose_name='Название'),
        ),
    ]
