# Generated by Django 3.2.3 on 2025-01-22 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='В минутах', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальное время приготовления - 10 минут.')], verbose_name='Время приготовления'),
        ),
    ]
